// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcRuznDIjKav4WOhDob3GxjtvMq1VnSZM',
    appId: '1:237568054706:web:33708b474e06e8bb5100ab',
    messagingSenderId: '237568054706',
    projectId: 'crmproject-a21e9',
    authDomain: 'crmproject-a21e9.firebaseapp.com',
    storageBucket: 'crmproject-a21e9.appspot.com',
    measurementId: 'G-DD3BPDRKKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP2Lec-k4n4lcJtdRuSFppdv3h1_dZ1YE',
    appId: '1:237568054706:android:8357edf1b3c1af585100ab',
    messagingSenderId: '237568054706',
    projectId: 'crmproject-a21e9',
    storageBucket: 'crmproject-a21e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0iag7naPrfo8MKHkxZfFK0Y47N3t7bQ',
    appId: '1:237568054706:ios:807fd210e862ad8c5100ab',
    messagingSenderId: '237568054706',
    projectId: 'crmproject-a21e9',
    storageBucket: 'crmproject-a21e9.appspot.com',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS0iag7naPrfo8MKHkxZfFK0Y47N3t7bQ',
    appId: '1:237568054706:ios:807fd210e862ad8c5100ab',
    messagingSenderId: '237568054706',
    projectId: 'crmproject-a21e9',
    storageBucket: 'crmproject-a21e9.appspot.com',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcRuznDIjKav4WOhDob3GxjtvMq1VnSZM',
    appId: '1:237568054706:web:4e53e14633860e385100ab',
    messagingSenderId: '237568054706',
    projectId: 'crmproject-a21e9',
    authDomain: 'crmproject-a21e9.firebaseapp.com',
    storageBucket: 'crmproject-a21e9.appspot.com',
    measurementId: 'G-7HYYSWZFRE',
  );
}
